### ISSUE TITLE
Git protocol fails when using sshkey parameter on Windows clients

### ISSUE THREAD

**Issue by djw** [hashicorp/go-getter#109]
When using the git protocol with an sshkey on Windows clients, go-getter fails due to its version checking code, as [git-for-windows](https://github.com/git-for-windows/git) doesn't use semver versioning.

For example, running `git version` will return `git version 2.17.0.windows.1`, which would need to use a hyphen after the patch version to be valid semver.

Due to this incorrect input, `checkGitVersion` is returning an error. This is preventing me using artifacts from a private git repository in a Nomad job running on Windows.

I'm not sure of the best fix for this... Perhaps Git 2.3 was released long enough ago that the version check could be removed?

**Comment by mitchellh** [comment]
Yeah, I don't feel good about checking for a Git version at all, but this was coming up reasonably often at one point in time hence we put it there. I think to be safest, maybe if we can't parse the output, we just ignore the version. So we still try to check it for those who support it.

**Comment by CSP197** [comment]
@mitchellh - Is this issue still open for contributions?
Or has #162 resolved the aforementioned bug?

**Comment by azr** [comment]
Hey @CSP197, ah I didn't see this issue, yes #162 fixed this problem, by just keeping what's before `.windows.` in the version. So not exactly what is said in https://github.com/hashicorp/go-getter/issues/109#issuecomment-439589409.

I think this is safe to close.
