### ISSUE TITLE
Add Google Cloud Storage Support

### ISSUE THREAD

**Issue by Ginja** [hashicorp/go-getter#110]
Would love to be able to fetch items from GCS.

**Comment by honnibal** [comment]
As a workaround until this is added, I've been using gcsfuse to mount the bucket: https://github.com/GoogleCloudPlatform/gcsfuse . This lets you use a file:// URL in getter

**Comment by eveld** [comment]
This would be great to have as it would allow  Nomad to also grab artifacts from GCS without them being public.

**Comment by davewongillies** [comment]
This has been added to go-getter https://github.com/hashicorp/go-getter/pull/170 and released in https://github.com/hashicorp/go-getter/releases/tag/v1.2.0
