### ISSUE TITLE
Http(s) getter does not follow redirects

### ISSUE THREAD

**Issue by yrobla** [hashicorp/go-getter#173]
I tried to download an URL that contains a 302 redirect. go-getter is giving me a 404 error, while if I use curl with -L flag, or wget, it's following the redirection properly and downloading the file. Redirections should be followed by default.

**Comment by azr** [comment]
Hello @yrobla, thanks for reporting, could you please share the url you are using so that I can reproduce ?

**Comment by yrobla** [comment]
Hi, thanks for the quick answer. I tried with that one: https://releases-rhcos.svc.ci.openshift.org/storage/releases//maipo/400.7.20190312.0/rhcos-maipo-400.7.20190312.0-qemu.qcow2.gz . I can get it with a curl -L, but if i use the same for go-getter i get a 404

**Comment by azr** [comment]
`//` is a special sequence for the go-getter described [here](https://github.com/hashicorp/go-getter#subdirectories).

It should work for you by removing one `/`, eg :

https://releases-rhcos.svc.ci.openshift.org/storage/releases/maipo/400.7.20190312.0/rhcos-maipo-400.7.20190312.0-qemu.qcow2.gz

**Comment by yrobla** [comment]
Ok thanks. It's quite usual to have those malformed urls with double slashes, specially when the value comes from parsing values. I'll check on my code to avoid it.
