### ISSUE TITLE
Add support for tar archives

### ISSUE THREAD

**Issue by ketzacoatl** [hashicorp/go-getter#19]
Some projects distribute with .zip or .tgz, others have only a .tar (example: https://github.com/AcalephStorage/consul-alerts distributes https://bintray.com/artifact/download/darkcrux/generic/consul-alerts-latest-linux-amd64.tar)

It seems that the go-getter library only supports .tgz or .bz2, but not uncompressed .tar by itself.

**Comment by mitchellh** [comment]
This would be simple enough. No short term plans to knock this out but if anyone wants to take a look at how the other decompressors work and their respective tests, I think you'll find its quite easy to implement. I'm sure we'll do it sometime "soon" though, since it does seem like a no-brainer!

**Comment by ketzacoatl** [comment]
You are totally right @mitchellh, given what's in place, this is the simplest exercise in go. I have very little skill with go, but I will see what I can do on my own.

**Comment by ketzacoatl** [comment]
OK, I think I have it (at least it builds and tests pass), but what would be a reasonable way to test this updated build either locally with Terraform or on a remote cluster with Nomad?

**Comment by ketzacoatl** [comment]
No pressure here, but I'm curious if I did this correctly?

**Comment by ketzacoatl** [comment]
no pressure, but I am still curious.

**Comment by ketzacoatl** [comment]
With https://github.com/hashicorp/go-getter/blob/master/decompress_tar.go, does `go-getter` now support decompressing `.tar` archives? Is this issue good to close?

**Comment by upccup** [comment]
now i use go-getter download foo.tar.gz file. it still report ERROR: *archive: gzip: invalid header*.

the foo.tar.gz is created by **tar -cvf  foo.tar.gz bar**

**Comment by ketzacoatl** [comment]
@dadgar, can this get a review, is it still relevant?

**Comment by ketzacoatl** [comment]
Yay! Thanks @schmichael!
