### ISSUE TITLE
AWS credentials not handled correctly

### ISSUE THREAD

**Issue by jbergknoff-rival** [hashicorp/go-getter#191]
There are various issues with the AWS credential handling when downloading from S3. #185 #157 #152 #22 https://github.com/gruntwork-io/terragrunt/pull/775

I'm less familiar with the AWS SDK for Go, but in my experience with those for JavaScript and Python, the credential handling here [1] looks like it can be made simpler and more robust by using the SDK as documented [2].

The particulars about communicating with the EC2 (or ECS) metadata API, reading the shared config or credentials file, choosing a region, etc., are all handled by the SDK's default credential provider chain. The explicit provider chain constructed in `getAWSConfig` lacks support for various edge cases.

Would you be open to a PR changing the way AWS sessions are created?

[1] https://github.com/hashicorp/go-getter/blob/da0323b9545e4b9d821e9c7d8ed4429e41d997ed/get_s3.go#L182-L217
[2] "Configuring Credentials" section on https://docs.aws.amazon.com/sdk-for-go/api/

**Comment by blockmar** [comment]
+1

I can verify that there still are issues with how Role based authentications are handled in `go-getter`:

Fails:
```
$ ./go-getter mybucket.s3-eu-north-1.amazonaws.com/path/my-file.jar my-file.jar 2019/07/05 12:57:01 Error downloading: AccessDenied: Access Denied
	status code: 403, request id: 18712XXXXCBE2CED, host id: iSKc/1xteeXXXXXXXXXXXXXXXs9ieOT2WjY2Q41YJYZFCpwG/E2P82bgmPANA=
```
Works:
```
$ aws s3 cp s3://mybucket/path/my-file.jar my-file.jar
download: s3://mybucket/path/myfile.jar to ./myfile.jar
```
(No AWS credentials set in environment nor credentials file)

**Comment by bashims** [comment]
I am working on a PR for this as we speak. The lack of support AWS profiles and STS (AssumeRole) is showstopper for us. Using the default credential providers should work just fine here.

**Comment by solarmosaic-kflorence** [comment]
Please fix this.
