### ISSUE TITLE
Support for virtual host style s3 uris

### ISSUE THREAD

**Issue by jcrowgey** [hashicorp/go-getter#199]
Amazon has published some guidelines which suggest migrating away from path-style s3 uris:

https://aws.amazon.com/blogs/aws/amazon-s3-path-deprecation-plan-the-rest-of-the-story/

go-getter seems to only support path-style, however:

https://github.com/hashicorp/go-getter/blob/30a49e438715626318447d8ac7166bb425b695dc/get_s3.go#L205

Or, perhaps I'm missing something, since I do see that virtual-host style uris are delectable:

https://github.com/hashicorp/go-getter/blob/30a49e438715626318447d8ac7166bb425b695dc/detect_s3.go#L53

**Comment by picatz** [comment]
Should be fixed with #283
