### ISSUE TITLE
Simpler syntax for git-over-ssh sources

### ISSUE THREAD

**Issue by phinze** [hashicorp/go-getter#21]
Refiling a request we had over in Terraform for a simpler - more conventional - format to fetch git over ssh.

https://github.com/hashicorp/terraform/issues/2172

```
git@github.com:user/repo

git@github.com:user/repo//subfolder
```

**Comment by mitchellh** [comment]
KEEP THE FAITH @phinze BECAUSE 30 MONTHS LATER THIS ISSUE IS RESOLVED.

PR #129
