### ISSUE TITLE
S3: Support for getting credentials from EC2 meta-data service when using IAM roles.

### ISSUE THREAD

**Issue by c4milo** [hashicorp/go-getter#22]
I can see go-getter using the EC2RoleProvider but I couldn't find where it was calling `creds.Get()` to download the actual credentials, from AWS metadata service. I ran across this issue while trying to use Nomad with a job using artifacts located in S3.

I also manually verified that retrieving credentials using CURL was possible in order to rule out IAM configuration issues.

**Comment by mitchellh** [comment]
I believe this is fixed with this: https://github.com/hashicorp/go-getter/commit/3142ddc1d627a166970ddd301bc09cb510c74edc

We weren't configured the EC2RoleProvider properly.
