### ISSUE TITLE
Lite version with fewer dependency

### ISSUE THREAD

**Issue by yujunz** [hashicorp/go-getter#236]
We plan to integrate go-getter in https://github.com/kubernetes-sigs/kustomize/pull/2169 since go-getter has everything we need in getting remote sources.

However, kustomize itself is integrated in kubectl which has dependency conflict with some modules used by go-getter.

I wonder if we can have a lite version of go-getter with fewer dependency, mainly stripping s3, gcs and cmd to reduce the transitive dependencies. (See https://github.com/yujunz/go-getter/commit/fc7e8cd6fd451576893995bd09ea616181e732cc). This will make go-getter easier to integrate in other tools as a library.

What do you think about it?

cc @monopole @Liujingfang1

**Comment by azr** [comment]
Hello there, thanks for opening; we currently started a `v2` branch with some breaking changes, it is not tagged yet and if you want to: one option we were considering would be to split the getters into sub modules, the `cmd` pkg can also be into a different submodule. Would you like to start working on this ?

For the  `v2`, we carved out a new `Request` struct from the `Client` struct; the `v2` can also tell where the file was put.

**Comment by yujunz** [comment]
That sounds interesting. Yes, I can contribute some time to splitting go-getter into sub modules.

Could you elaborate a bit the goals and no goals `v2` so that I can understand the context better. And if there is already some work going on. Where can I find more details and follow the progress? Thanks.

**Comment by azr** [comment]
Everything is in the v2 https://github.com/hashicorp/go-getter/tree/v2 branch and the request/client splitting is already in there. The Packer project which I help maintain needed some features which were breaking changes so I made them. PRs are here: #230 #231 #232 

I am also considering this other breaking change that some users requested already in #207 and #193

**Comment by azr** [comment]
Actually I think it would be better to move the conversation to #193, closing this one. I'll recap there.
