### ISSUE TITLE
S3 URLs starting with https:// are not properly detected.

### ISSUE THREAD

**Issue by c4milo** [hashicorp/go-getter#24]
Ex: https://my-bucket.amazonaws.com/my/path/archive.tar.gz

**Comment by mitchellh** [comment]
You're telling go-getter at that point to use the `https` protocol. 

You can force it (advanced feature, in the README) like this `s3::https://` or you can just drop `https` and it should use the API to grab it over HTTPS. You can see examples of the S3 detection here: https://github.com/hashicorp/go-getter/blob/master/detect_s3_test.go

And you can find more about the `::` syntax in the README, though I've found it rarely has to be used.

**Comment by c4milo** [comment]
Thanks for the quick response @mitchellh.

**Comment by c4milo** [comment]
I ran into this issue with Nomad artifacts. This usage wasn't obvious there.

**Comment by mitchellh** [comment]
Yeah even I ran into it :( I'm not sure what to do about it. I thought about running detectors on URLs with protocols as well and requiring the inverse (forcing `http::https://` if you wanted it over HTTP and not S3 API) but I'm not sure.

**Comment by c4milo** [comment]
@mitchellh, I think it would be just fine making it more explicit in Nomad's documentation.
