### ISSUE TITLE
Error compiling with go 1.14

### ISSUE THREAD

**Issue by dllz** [hashicorp/go-getter#242]
Hi. 

I just started using go getter to download some basic files over the web. 

After adding the module using:

```go get github.com/hashicorp/go-getter```
My first compile with the project produces this error: 

```# github.com/hashicorp/go-getter
../../../go/pkg/mod/github.com/hashicorp/go-getter@v1.4.1/get_http.go:91:24: g.Header.Clone undefined (type http.Header has no field or method Clone)
../../../go/pkg/mod/github.com/hashicorp/go-getter@v1.4.1/get_http.go:172:24: g.Header.Clone undefined (type http.Header has no field or method Clone)
```
Anyone got any advice as to what I missed? 

Thanks in advance

**Comment by oligot** [comment]
Hi,

I also got this error, but when using Go version 1.12.
The Clone method has been [added in version 1.13](https://golang.org/pkg/net/http/#Header.Clone) and according to commit 52561d917139cde51332028978627cd2f8b42d6c, this is the minimum supported version for go-getter.

You are probably using a go version prior to 1.13.
You can check your version by running the command
> go version

which for me returns this:
> go version go1.14.2 linux/amd64
