### ISSUE TITLE
Add support for newer dot region AWS S3 virtual host style paths

### ISSUE THREAD

**Issue by picatz** [hashicorp/go-getter#263]
Following up on https://github.com/hashicorp/nomad/issues/8454, the [current tests](https://github.com/hashicorp/go-getter/blob/3f60ec5cfbb2a39731571b9ddae54b303bb0a969/detect_s3_test.go#L12) don't include the newer virtual hosted style syntax, and doesn't [seem](https://github.com/hashicorp/go-getter/blob/3f60ec5cfbb2a39731571b9ddae54b303bb0a969/detect_s3.go#L32) to be supported. This is causing valid S3 paths to fail for Nomad's [`artifact`](https://www.nomadproject.io/docs/job-specification/artifact#artifact-stanza) stanza, and is a pain to debug / manually spot.

The S3 detector implementation should be adjusted to support the newer virtual host style paths using the dot region syntax.

## Example

Newer virtual host style with S3 **dot** region endpoint structure:
`https://legacy-player-resources.s3.eu-west-2.amazonaws.com/...`
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; ☝️  

Older virtual host style with S3 **dash** region endpoint structure:
`https://legacy-player-resources.s3-eu-west-2.amazonaws.com/...`
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; ☝️ 

The older dash-style that _is supported_ is actually discouraged in the [S3 documentation](https://docs.aws.amazon.com/AmazonS3/latest/dev/UsingBucket.html#access-bucket-intro):

> We recommend that you **do not use** this endpoint structure in your requests.

### Phasing out S3 Path Style

To add to the complications, the other "path style" that is also supported will be [soon phased out](https://aws.amazon.com/blogs/aws/amazon-s3-path-deprecation-plan-the-rest-of-the-story/):

> Support for the path-style model continues for buckets created on or before September 30, 2020. Buckets created after that date must be referenced using the virtual-hosted model.

**Comment by scalp42** [comment]
@picatz any timeline on this? I believe it's now broken with new buckets

**Comment by picatz** [comment]
@scalp42 sorry I don't have a timeline for this, yet! 

Need to review/merge #282, cut a release, and get the updates in the required projects (like https://github.com/hashicorp/nomad/issues/9050)

**Comment by picatz** [comment]
Fix released in [v1.5.1](https://github.com/hashicorp/go-getter/releases/tag/v1.5.1)

**Comment by scalp42** [comment]
awesome! thanks @picatz
