### ISSUE TITLE
Proxy support

### ISSUE THREAD

**Issue by Gerrrr** [hashicorp/go-getter#27]
Hi,

While using Nomad, I got stuck with a problem which might be related to go-getter.
In the Nomad job I specify an artifact to download and the job fails because the download times out:
```
GET error: Get https://raw.githubusercontent.com/FRosner/nomad-docker-wrapper/master/nomad-docker-wrapper: dial tcp 23.235.43.133:443: i/o timeout
```

The machine I am using is behind the proxy, can this cause the problem? `http_proxy` and `https_proxy` variables are set, but can it be the case that go-getter is not picking them?

Original Nomad issue: https://groups.google.com/forum/#!topic/nomad-tool/rwLe3rIE2ZI

Thank you in advance!

**Comment by mitchellh** [comment]
We do respect those. I tested to verify and got it to work locally:

```
$ http_proxy=http://127.0.0.1:8080 go-getter http://www.example.com/ foo
2016/06/13 10:34:45 Success!
```

And my proxy verifies it proxied the connection:

```
2016/06/13 10:34:45 [004] INFO: Got request / www.example.com GET http://www.example.com/
2016/06/13 10:34:45 [004] INFO: Sending request GET http://www.example.com/
2016/06/13 10:34:45 [004] INFO: Received response 200 OK
2016/06/13 10:34:45 [004] INFO: Copying response to client 200 OK [200]
2016/06/13 10:34:45 [004] INFO: Copied 1270 bytes to client error=<nil>
```

Unfortunately this looks like something else. Is Nomad perhaps removing these env vars?
