### ISSUE TITLE
Support zstd

### ISSUE THREAD

**Issue by yaroot** [hashicorp/go-getter#270]
It's much much faster than xz for both compression and decompression while maintaining similar result.

There are 2 implementation available for go, both are 3 clause BSD

https://github.com/DataDog/zstd  the go wrapper for facebook/zstd
https://github.com/klauspost/compress  a pure go implementation but around 1.5x slower than C implementation (https://github.com/dgraph-io/badger/pull/1176#issuecomment-573635053)

**Comment by jboero** [comment]
+1 this applies to a Nomad feature request of mine.
