### ISSUE TITLE
Security Error on go get: checksum mismatch

### ISSUE THREAD

**Issue by clarkmcc** [hashicorp/go-getter#294]
I'm running go version `go1.15.4 darwin/amd64` and got this error when running `go get github.com/hashicorp/go-getter`.

```
go: downloading github.com/hashicorp/go-getter v1.5.1
go get github.com/hashicorp/go-getter: github.com/hashicorp/go-getter@v1.5.1: verifying module: checksum mismatch
        downloaded: h1:LZ49OxqBBtdKJymlpX7oTyqGBQRg4xxQDyPW4hzoZqM=
        sum.golang.org: h1:lM9sM02nvEApQGFgkXxWbhfqtyN+AyhQmi+MaMdBDOI=

SECURITY ERROR
This download does NOT match the one reported by the checksum server.
The bits may have been replaced on the origin server, or an attacker may
have intercepted the download attempt.

For more information, see 'go help module-auth'.
```

I also tried running `go clean -modcache` but it had no affect.

**Comment by azr** [comment]
Hello @clarkmcc, that is odd; when I install/download go-getter v1.5.1 it gets me the `h1:LZ49OxqBBtdKJymlpX7oTyqGBQRg4xxQDyPW4hzoZqM=` version. Do you still have the issue; could it be that sum.golang.org was outdated ?

**Comment by clarkmcc** [comment]
I don't have any proxy configured. If it's just my machine, I'll do some more experimenting. Thanks for confirming! @azr 
```
GOPROXY="direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
```

**Comment by azr** [comment]
Gotcha, I see one diff between our configs, mine has: `GOPROXY="https://proxy.golang.org,direct"`

**Comment by clarkmcc** [comment]
@azr Thanks, I'll swap that out and give it a try
