### ISSUE TITLE
GitGetter.setupGitEnv() breaks `sshCommand` config attribute

### ISSUE THREAD

**Issue by nl-brett-stime** [hashicorp/go-getter#299]
Context:
Recent versions of git (>= v2.10) support setting an SSH command via .gitconfig files. E.g., https://stackoverflow.com/a/38474137/93345 .

This is particularly useful when coupled with another somewhat recent feature of conditional config imports e.g., https://stackoverflow.com/a/36296990/93345 .

Problem:
The setupGitEnv() function in get_git.go specifies a `GIT_SSH_COMMAND` environment variable, *even when an ssh key file is not explicitly set in the git repo URL via the `sshkey` query parameter*.

When there is no query parameter for `sshkey`, the `GIT_SSH_COMMAND` environment variable should be left unset. Presently, it ends up being set to `GIT_SSH_COMMAND=ssh`, which breaks configuration via .gitconfig files.

**Comment by nl-brett-stime** [comment]
Link to function at issue:
https://github.com/hashicorp/go-getter/blob/f9b50ddb4f9142922f73aa3812d82cc90d50a884/get_git.go#L239-L273

**Comment by raffraffraff** [comment]
Thanks @msmans - it's horrible to ask everyone in the team to do this. In my case, I'm working around it for my _work identity_ simply by making it the default one in `~/.ssh/config`:

```
IdentityFile /home/myuser/.ssh/work_key
```

This fixes `terraform init` in work, and I can swap around my `.gitconfig` overrides to match.

**Comment by soar** [comment]
Why is this issue closed, if the problem still exists?

**Comment by crw** [comment]
@soar There have been multiple closed PRs on this issue since the original report. At this point it would be more useful to open a new issue describing the symptoms you are seeing and the use case, if you are experiencing problems with the given functionality. Thanks!

**Comment by soar** [comment]
My apologies. I just realized, that it works with the newest Terraform. Thank you a lot!
