### ISSUE TITLE
HTTP Basic auth support?

### ISSUE THREAD

**Issue by adrianlop** [hashicorp/go-getter#32]
Hi,

Any plans on adding parameters for http basic auth? I'm using Nomad and would like to download artifacts from a secured JFrog Artifactory.

thanks in advance!

**Comment by mitchellh** [comment]
Great idea and not too difficult to do, we'd love to support this.

**Comment by adrianlop** [comment]
thanks @mitchellh. I'll work on a PR these next days.

**Comment by Ashald** [comment]
Oh wow.... I thought such a basic option was supported from the very first version... Hope #34 will get into next release as it's absolute blocker for us. :(

**Comment by dadgar** [comment]
Hey all go-getter already supports this with normal basic auth formatting:
`http://<user>:<password>@foo.com/bar`
