### ISSUE TITLE
Running go-getter always returns 128 for a github repo.

### ISSUE THREAD

**Issue by darren-west** [hashicorp/go-getter#35]
The command go-getter github.com/hashicorp/nomad ./test returns the error

2016/10/05 10:29:50 Error downloading: /usr/bin/git exited with 128: Cloning into '/tmp/getter-git236954800'...
fatal: repository 'https://github.com/hashicorp/' not found

Am I misunderstanding? Or can someone help

**Comment by chreble** [comment]
Same here
