### ISSUE TITLE
Failed to download artifact : getter subprocess failed: exit status 1

### ISSUE THREAD

**Issue by spanner4715** [hashicorp/go-getter#447]
Hello, this is Spanner. I'm currently trying to download an artifact and running that on Nomad. However, I keep encountering this issue "Failed to download artifact : getter subprocess failed: exit status 1". I noticed if I download this file by manually, there would be a "sbin" file whereas I couldn't see that on Nomad. I'm not sure whether this is the root which cause me failure in successfully downloading artifact.
**Error**
![Screenshot from 2023-08-15 22-32-22](https://github.com/hashicorp/go-getter/assets/103509243/25640237-88f8-4883-b2cd-bb88407e540f)

### Manually download
![Screenshot from 2023-08-16 14-38-25](https://github.com/hashicorp/go-getter/assets/103509243/14b64d4f-69a0-41e9-ac3e-20d93d6082b9)

### Nomad couldn't download "sbin" folder
![Screenshot from 2023-08-16 14-33-39](https://github.com/hashicorp/go-getter/assets/103509243/482cff9e-7c99-44c7-b5da-37fd278d524a)

**Comment by kurekbharath** [comment]
@spanner4715 Could you please explain what changes are performed to fix this issue ?
