### ISSUE TITLE
Loaders Integration With The Env

### ISSUE THREAD

**Issue by gastraight** [hashicorp/go-getter#462]
Hi.
Is the loaders implementation it self is ran by the library just on specific protocol level or should  one care for related prerequisites (e.g. `git`, `aws-sdk` etc.) to be presented in the environment?

How would the loader be integrated with the env configuration for related tools (e.g. GIT_SSH_COMMAND, ~/.git, ~/.aws ~/.ssh)?

I.e. Does it rely/depend on sys implementation and is it integrated with a configured env if any?

Thank you

**Comment by crw** [comment]
Hi @gastraight, `go-getter` is a library that is used internally by several projects at HashiCorp (for example, Terraform and Nomad). It is not generally thought of as a library for use outside of a HashiCorp project context. You can try asking your questions in the [the community forum](https://discuss.hashicorp.com/). There is not a great section for this question, you can try the Terraform section. Thanks for your interest! I hope you find the answers to your questions.
