### ISSUE TITLE
Custom App Specific Url Options

### ISSUE THREAD

**Issue by gastraight** [hashicorp/go-getter#463]
Hi
Except for loader specific url options is it possible somehow to extend url format with  application level specific ones

As I understand getter url is not just a regular one for `net/url.Parse`? Would be just to slice an url after `?` be  general safe enough?

Or could it be maybe achieved with custom detector somehow that would transform url extracts the info but doesn't resolve the content it self and bypass it for other loaders?

Thank you

**Comment by crw** [comment]
Please see https://github.com/hashicorp/go-getter/issues/462#issuecomment-1783397409. Thanks!
