### ISSUE TITLE
How to Determinate GatAny Results

### ISSUE THREAD

**Issue by gastraight** [hashicorp/go-getter#464]
Hi
As [GetAny](https://github.com/hashicorp/go-getter/blob/v2.2.1/get.go#L119) accepts in general file/dir urls but handles them a bit. in different way is the a way to determine how downloaded content should be treated? I.e. should the `dest` or `dest/url_basename` be addressed?

As well as was it an arch being unpacked?

Thank you.

**Comment by gastraight** [comment]
P.S. For `git` getter as `https://github.com/hashicorp/go-getter.git//testdata` format is supposed to refer sub directories. So how the exact file could be located?

**Comment by crw** [comment]
Please see https://github.com/hashicorp/go-getter/issues/462#issuecomment-1783397409. Thanks!
