### ISSUE TITLE
Auto yes when cloning git repos

### ISSUE THREAD

**Issue by dadgar** [hashicorp/go-getter#55]
When using go-getter programmatically and cloning repositories using git over ssh it would be good to have an AutoYes config parameter to move pass this:

```
The authenticity of host 'github.com (192.30.253.113)' can't be established.
RSA key fingerprint is SHA256:nThbg6kXUpJWGl7E1IGOCspRomTxdCARLviKw6E5SY8.
Are you sure you want to continue connecting (yes/no)?
```

**Comment by mitchellh** [comment]
Is this fixed is that why this was closed?

**Comment by dadgar** [comment]
No it is not fixed. I closed it since there is a sane workaround of using `ssh-keyscan` to add the domains public keys to the `~/.ssh/known_hosts` file which is probably a safer solution than auto yesing any returned address.
